### ISSUE TITLE
Adding animation to the conveyor belt on 'WhyLitmus?' tab

### ISSUE THREAD

**Issue by S-ayanide** [litmuschaos/website-litmuschaos#117]
#### SUMMARY

The requirement to animate the conveyor belt carrying the test tubes in a way that it stays in motion and new test tubes gets generated on the left after each test tube reaches the end. preferably using physics-based animation/gatsby substitute for physics-based animation package.

#### SCREENSHOT

<img src="https://i.ibb.co/jrKj0CW/conveyor-Belt.png" alt="Conveyor Belt" />

#### COMPONENTS WHICH REQUIRE CHANGE

* ConveryorBelt.tsx [A GraphQL fluid image fetch]

```
File: ./whylitmus/Features.tsx

Line 94 <ConveryorBelt />
```

#### ISSUE TYPE

* Feature Request

#### CONTACT PERSON

* [Sayan Mondal](https://github.com/S-ayanide)
* [Arkajyoti Mukherjee](https://github.com/arkajyotiMukherjee)

#### GUIDELINES

* Sign your commits by doing a `git commit -s -m "<commit message>"` [**Required**]
* Add comments based on the logic you've implemented

> Please send all Pull Requests to `staging` branch and not `master`

Thanks for taking the time to read this issue. In order for Litmus to clarify your doubts effectively, provide us a few hours to reply back.

**Comment by mehabhalodiya** [comment]
Hey
I would like to contribute.
Can someone please guide me through this?

**Comment by arkajyotiMukherjee** [comment]
@mehabhalodiya Thanks for your interest, unfortunately, this was for our old design. We'll create new issues for the current design soon. I'll be closing this issue. Please consider staring/watching this repo to get notified of the new issues.

**Comment by mehabhalodiya** [comment]
@arkajyotiMukherjee Please do opening of new issues, particularly `good first issues`.
Looking forward to contribute as well :)
Thank you.

**Comment by arkajyotiMukherjee** [comment]
Tagging @venkatexh, @SahilKr24 and @hrishavjha to the thread.
