### ISSUE TITLE
Adding Top-to-Bottom Page Transition in Litmus Website

### ISSUE THREAD

**Issue by S-ayanide** [litmuschaos/website-litmuschaos#119]
#### SUMMARY

Using [gatsby-plugin-transition-link](https://www.gatsbyjs.com/docs/adding-page-transitions-with-plugin-transition-link/) to add top to bottom page transition in the Litmus Website. This transition link change should not affect previously passed props or state changes in the pages.

####TRANSITION TYPE

For a more detailed understanding click on 'Go to page 2 that way 👇 and animate in the next page' of [this demo](https://gatsby-plugin-transition-link.netlify.app/). This is the behaviour we are expecting on navigating to different pages on clicking the navbar items. *Except Getting Started at Navbar*

#### COMPONENTS WHICH REQUIRE CHANGE

* Nav.tsx

```
File: ./nav/Nav.tsx
```

#### ISSUE TYPE

* Feature Request

#### CONTACT PERSON

* [Sayan Mondal](https://github.com/S-ayanide)
* [Arkajyoti Mukherjee](https://github.com/arkajyotiMukherjee)

#### GUIDELINES

* Sign your commits by doing a `git commit -s -m "<commit message>"` [**Required**]
* Add comments based on the logic you've implemented

> Please send all Pull Requests to `staging` branch and not `master`

Thanks for taking the time to read this issue. In order for Litmus to clarify your doubts effectively, provide us a few hours to reply back.

**Comment by arkajyotiMukherjee** [comment]
Closing old issues.
