### ISSUE TITLE
[UX] Fix Navbar menu in mobile

### ISSUE THREAD

**Issue by ChaituVR** [litmuschaos/website-litmuschaos#120]
Related to #118 

![Screenshot_20200922-135412](https://user-images.githubusercontent.com/15967809/93859587-70e03280-fcdb-11ea-9869-bfa9edcdd324.png)

On mobile Navbar doesn't scroll with menu, and it doesn't close until user scroll backs to top
i think it should either scroll with navbar or should automatically close on scroll

**Comment by arkajyotiMukherjee** [comment]
PR #123 fixes this issue
