### ISSUE TITLE
[UX] Get started with Litmus links in mobile

### ISSUE THREAD

**Issue by ChaituVR** [litmuschaos/website-litmuschaos#121]
For #118 

In mobile inside "Get started with Litmus" section if we click on any link, it seems like nothing is happening 
![image](https://user-images.githubusercontent.com/15967809/93860821-4000fd00-fcdd-11ea-8d9a-6cf7b56f2903.png)

#### Suggested behaviour:
to give user better experience, on click of any of these links should scroll up to terminal to display terminal

![image](https://user-images.githubusercontent.com/15967809/93861161-b3a30a00-fcdd-11ea-9264-ec75df9de7c4.png)

**Comment by arkajyotiMukherjee** [comment]
Closing old issues as the design has changed.
