### ISSUE TITLE
Get Started buttons are redirecting to a wrong link

### ISSUE THREAD

**Issue by eran-levy** [litmuschaos/website-litmuschaos#174]
The Get Started links redirecting to: https://docs.litmuschaos.io/docs/getstarted/
instead of https://docs.litmuschaos.io/docs/getting-started/installation/

**Comment by arkajyotiMukherjee** [comment]
Assigned the issue to appropriate people. Thanks @eran-levy for pointing it out.

**Comment by SahilKr24** [comment]
Thank you for reporting the issue @eran-levy but updates to the current [litmuschaos.io](https://litmuschaos.io) are mapped to [this](https://github.com/litmuschaos/litmus-website-2) repository now.
We will archive this repository to avoid further confusion.
